BUSINESS_TYPE_INIT_CIF = "CIF"
BUSINESS_TYPE_EKYC_AUDIT = "KSS_EKYC"
BUSINESS_TYPE_OPEN_CASA = "OPEN_CASA"


BUSINESS_TYPES = {
    BUSINESS_TYPE_INIT_CIF: "Mở CIF",
    BUSINESS_TYPE_OPEN_CASA: "Mở mới tài khoản thanh toán",
    BUSINESS_TYPE_EKYC_AUDIT: "Kiểm soát sau EKYC"
}
