MAIN_CARD = "B"
SUB_CARD = "S"

GW_DEFAULT_ATM_CARD_ACCOUNT_PROVIDER = 2
GW_DEFAULT_CARD_AUTO_RENEW = "N"
GW_DEFAULT_CARD_RELATION_TO_PRIMARY = "R"
GW_DEFAULT_CARD_BILL_OPTION = "H"
GW_DEFAULT_CARD_STATEMENT_DELIVERY_OPTION = 'M'

GW_DEFAULT_VISA_EXPIRE_DATE = "000000"
GW_DEFAULT_EMAIL = "default@scb.com.vn"

GW_DEFAULT_CUSTOMER_NATIONALITY = "VN"
GW_DEFAULT_CUSTOMER_RESIDENT_STATUS = "L"
GW_DEFAULT_CUSTOMER_RESIDENT_TYPE = "O"
GW_DEFAULT_CUSTOMER_EDUCATION = "07"

GW_CUST_TITLE_MR = "MR"
GW_CUST_TITLE_MRS = "MRS"

CRM_CUST_TITLE_MR = "ONG"
CRM_CUST_TITLE_MRS = "BA"

CRM_DELIVERY_ADDRESS_FLAG_FALSE = 0

GW_DEFAULT_RESIDENT_SINCE = "000000"
GW_DEFAULT_EMPLOYEE_SINCE = "000000"
GW_DEFAULT_EMPLOYEE_DURATION = "0"

GW_DEFAULT_ZERO = "0"
GW_DEFAULT_spcEmpWorkNat = "U"
GW_DEFAULT_emerRelt = "R"
GW_DEFAULT_decsnStat = "AM"

GW_DEFAULT_casaAcctTyp = "20"
GW_DEFAULT_apprvDeviation = "NOTE"
GW_DEFAULT_smsInfo = "1"
GW_DEFAULT_narrative = "CRM WS"
GW_DEFAULT_delivOpt = "O"

MARITAL_STATUS_SINGLE = "S"
MARITAL_STATUS_MARRIED = "M"
MARITAL_STATUS_DISVORSED = "D"
MARITAL_STATUS_OTHERS = "O"

IDENTITY_DOCUMENT_TYPE_PASSPORT_CODE = "HO_CHIEU"
IDENTITY_DOCUMENT_TYPE_PASSPORT = "P"
IDENTITY_DOCUMENT_TYPE_NEW_IC = "N"

RESIDENT = "R"

GW_DEFAULT_QUICK = "Q"
GW_DEFAULT_NORMAL = "N"
