MAIN_CARD = "B"
SUB_CARD = "S"

LOCAL_CREDIT_ACCOUNT_PROVIDER = 3
PREPAID_CARD_ACCOUNT_PROVIDER = 5
ATM_CARD_ACCOUNT_PROVIDER = 2
MC_VS_CREDIT_CARD_ACCOUNT_PROVIDER = 8

GW_CUST_TITLE_MR = "MR"
GW_CUST_TITLE_MRS = "MRS"

CRM_CUST_TITLE_MR = "ONG"
CRM_CUST_TITLE_MRS = "BA"

CRM_DELIVERY_ADDRESS_FLAG_FALSE = 0
