EKYC_DATE_FORMAT = '%d/%m/%Y'
EKYC_DEFAULT_VALUE = ""
MENU_CODE = 'EKYC'
MENU_CODE_VIEW = "EKYC_VIEW"
GROUP_ROLE_CODE_VIEW = 'EKYC_VIEW'
GROUP_ROLE_CODE_AP = 'EKYC_AP'
GROUP_ROLE_CODE_IN = 'EKYC_IN'
is_success = 'Success'

EKYC_FLAG = 1
