GW_REPONSE_STATUS_SUCCESS = 1
GW_CASA_REPONSE_STATUS_SUCCESS = '00'
GW_ENDPOINT_URL_RETRIEVE_CUS_REF_DATA_MGMT = "/customerrefdatamgmt/v1.0/rest/retrieveCustomerRefDataMgmt"
GW_ENDPOINT_URL_RETRIEVE_CURRENT_ACCOUNT_CASA = "/currentaccount/v1.0/rest/retrieveCurrentAccountCASA"
GW_ENDPOINT_URL_RETRIEVE_CURRENT_ACCOUNT_CASA_FROM_CIF = '/currentaccount/v1.0/rest/selectCurrentAccountFromCIF'
GW_ENDPOINT_URL_RETRIEVE_DEPOSIT_ACCOUNT_FROM_CIF = '/depositaccount/v1.0/rest/selectDepositAccountFromCIF'
GW_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
CURRENT_ACCOUNT_FROM_CIF = "CurrentAccountFromCIF"
DEPOSIT_ACCOUNT_FROM_CIF = "DepositAccountFromCIF"
