IDM_MENU_CODE_CIF = "CIF"
IDM_GROUP_ROLE_CODE_APPROVAL = "PD_CIF"
IDM_PERMISSION_CODE_KSV = "KSV_CIF"

IDM_MENU_CODE_OPEN_CIF = "QLKH"
IDM_GROUP_ROLE_CODE_OPEN_CIF = "MO_CIF"
IDM_PERMISSION_CODE_OPEN_CIF = "TAO_CIF"
