IDM_MENU_CODE_TTKH = "TTKH"

IDM_GROUP_ROLE_CODE_GDV = "GDV"
IDM_PERMISSION_CODE_GDV = "GDV"

IDM_GROUP_ROLE_CODE_KSV = "PD_KSV"
IDM_PERMISSION_CODE_KSV = "PD_KSV"

IDM_PERMISSION_CODE_KSS = "KSS_KSV"
